# Generated by Django 4.2.17 on 2025-02-03 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_menstrualdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menstrualdata",
            name="period_length",
        ),
    ]
