# Generated by Django 4.2.17 on 2025-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_menstrualdata_period_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="menstrualdata",
            name="period_length",
            field=models.IntegerField(default=5),
        ),
    ]
