# Generated by Django 4.2.17 on 2025-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_chatsession_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("content", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("published_date", models.DateTimeField()),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="Keywords matched"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="articles", to="users.category"
                    ),
                ),
            ],
        ),
    ]
