# Generated by Django 4.2.17 on 2025-03-05 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_slideshowimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SlideshowImage",
        ),
    ]
