# Generated by Django 4.2.17 on 2025-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_delete_slideshowimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_bot_name",
            field=models.CharField(default="Luna", max_length=100),
        ),
    ]
