# Generated by Django 4.2.17 on 2025-03-12 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_customuser_preferred_bot_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="symptomlog",
            unique_together={("user", "date")},
        ),
    ]
