# Generated by Django 4.2.17 on 2025-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_contactsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
